import type { AttributeContext } from "./attributeMetadata";

/**
 * Zuordnung sichtbarer Metrik-Labels zu Attribut-Registry-Eintraegen
 * (attributeMetadata). Extrahiert aus InspectorPanel (Stage 2 des
 * UX-Redesigns), Inhalte unveraendert.
 */

export type AttributeHint = {
  key: string;
  context: AttributeContext;
};

export const metricAttributeHints: Record<string, AttributeHint> = {
  "Punktcode": { key: "code", context: "insar-point" },
  "Track / LOS": { key: "los", context: "insar-point" },
  "Geschwindigkeit": { key: "velocity", context: "insar-point" },
  "Geschwindigkeit Std.": { key: "velocity_std", context: "insar-point" },
  "Kohaerenz": { key: "coherence", context: "insar-point" },
  "Deformations-Std.": { key: "std_def", context: "insar-point" },
  "InSAR-Hoehe": { key: "height", context: "insar-point" },
  "Hoehe Std.": { key: "height_std", context: "insar-point" },
  "Beschleunigung": { key: "acceleration", context: "insar-point" },
  "Beschleunigung Std.": { key: "acceleration_std", context: "insar-point" },
  "Saisonale Amplitude": { key: "season_amp", context: "insar-point" },
  "Saisonale Amplitude Std.": { key: "s_amp_std", context: "insar-point" },
  "Saisonale Phase": { key: "season_phs", context: "insar-point" },
  "Saisonale Phase Std.": { key: "s_phs_std", context: "insar-point" },
  "Amplitude Mittel": { key: "amp_mean", context: "insar-point" },
  "Amplitude Std.": { key: "amp_std", context: "insar-point" },
  "Effektive Flaeche": { key: "eff_area", context: "insar-point" },
  "Einfallswinkel": { key: "incidence_angle", context: "insar-point" },
  "Laengengrad": { key: "lon", context: "insar-point" },
  "Breitengrad": { key: "lat", context: "insar-point" },
  "Terrain-Quelle": { key: "source", context: "terrain" },
  "Terrain-Aufloesung": { key: "resolution_m", context: "terrain" },
  "Gelaendehoehe": { key: "elevation_m", context: "terrain" },
  "Mittlere Gelaendehoehe": { key: "elevation_mean_m", context: "terrain" },
  "Gelaendehoehe min/max": { key: "elevation_min_m", context: "terrain" },
  "Hangneigung": { key: "slope_deg", context: "terrain" },
  "Hangneigung Mittel / Max": { key: "slope_mean_deg", context: "terrain" },
  "Exposition": { key: "aspect_deg", context: "terrain" },
  "Reliefspanne": { key: "relief_range_m", context: "terrain" },
  "Aktiver Lauf": { key: "run_id", context: "ml-run" },
  "Run-Status": { key: "status", context: "ml-run" },
  "Pipeline": { key: "pipeline", context: "ml-run" },
  "Label": { key: "label", context: "ml-point" },
  "Qualitaetswert": { key: "quality_score", context: "ml-point" },
  "Anomaliewert": { key: "anomaly_score", context: "ml-point" },
  "Cross-Track-Konsistenz": { key: "cross_track_consistency", context: "ml-point" },
  "Gebaeude": { key: "building_id", context: "ml-point" },
  "Abstand zum Gebaeude": { key: "distance_m", context: "ml-point" },
  "Clusterrolle / Wahrscheinlichkeit": { key: "cluster_role", context: "ml-point" },
  "Cluster-Ausreisserwert": { key: "cluster_outlier_score", context: "ml-point" },
  "Cluster-Ausreisser": { key: "cluster_outlier", context: "ml-point" },
  "Lokale Abweichung": { key: "local_deviation", context: "ml-point" },
  "Regel-Penalty": { key: "rule_penalty", context: "ml-point" },
  "Fuer Scoring genutzt": { key: "kept_for_scoring", context: "ml-point" },
  "Gate-Gruende": { key: "gate_reasons", context: "ml-point" },
  "Zuordnung": { key: "assignment_method", context: "ml-point" },
  "Track-Stuetzung": { key: "track_point_count", context: "ml-point" },
  "Detektorwerte": { key: "detector_scores", context: "ml-point" },
  "Degradierungsgrund": { key: "degraded_reason", context: "ml-point" },
  "Quelle": { key: "source", context: "building" },
  "Gebaeude-ID": { key: "building_id", context: "building" },
  "Gebaeudehoehe": { key: "height", context: "building" },
  "Name": { key: "name", context: "building" },
  "Typ": { key: "building_type", context: "building" },
  "Bewegung": { key: "building_motion_mm_a", context: "ml-building" },
  "Zuverlaessigkeit": { key: "building_reliability_score", context: "ml-building" },
  "Status": { key: "building_status", context: "ml-building" },
  "Run-zugeordnete Punkte": { key: "point_count", context: "ml-building" },
  "Behalten / ausgeschlossen / Rauschen": { key: "kept_point_count", context: "ml-building" },
  "Bewegung / Status": { key: "building_motion_mm_a", context: "ml-building" },
  "Retuning-Flags": { key: "reliability_penalties", context: "ml-building" },
  "Track-Uebereinstimmung": { key: "track_agreement_score", context: "ml-building" },
  "Retuning-Anpassungen": { key: "reliability_penalties", context: "ml-building" },
  "Cluster / belastbar": { key: "cluster_count", context: "ml-building" },
  "Differenzielle Bewegung": { key: "differential_motion_level", context: "ml-building" },
  "Hauptcluster": { key: "main_cluster_by_track", context: "ml-building" },
  "Track-Bewegung": { key: "track_motion_mm_a", context: "ml-building" },
  "Median-Abstand": { key: "median_distance_m", context: "ml-building" },
  "Mittlere Qualitaet": { key: "avg_quality_score", context: "ml-building" },
  "Mittlere Anomalie": { key: "avg_anomaly_score", context: "ml-building" },
  "Mittlere Cross-Track-Konsistenz": {
    key: "avg_cross_track_consistency",
    context: "ml-building",
  },
};
